### ISSUE TITLE
Arxan and Xor.

### ISSUE THREAD

**Issue by Enjoyop** [Yura3313/UkrainianStars#2]
Hi, I'm working on CoC too.
I know a little about arxan jumping, but...
How can I get rid of Xor?
There is no xor encryption from the your libg.so file, may I ask how you did it?

**Comment by Yurab0b** [comment]
Hi, i didn't do it, i just used BSD's apk for modding which has everything decrypted and bypasses the signature verification.
Maybe for clash of clans there is some thing similar ¯\_(ツ)_/¯
